spring.application.name=rpgdemobox

spring.datasource.url=jdbc:mysql://localhost:3306/rpgdemobox
spring.datasource.username=root
spring.datasource.password=zipzopzooey
spring.jpa.hibernate.ddl-auto=update
